"""
RecHunter Monitoring Engine
===========================
Schedules and runs availability checks against Recreation.gov using APScheduler.

Supports three watch modes:
- DROP_TIME: Burst-checks every 3s for 90s at the configured drop time, then
  falls back to the normal poll interval.
- CANCELLATION: Recurring interval checks for cancellation openings.
- ONE_SHOT: Runs a single immediate check and marks the watch as completed.
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import datetime, timedelta, timezone
from typing import Callable, Optional, Awaitable, Set, Dict

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.date import DateTrigger
from apscheduler.triggers.interval import IntervalTrigger

from recsniper.models import (
    AvailabilitySlot,
    CheckResult,
    EventLog,
    Watch,
    WatchMode,
    WatchStatus,
)
from recsniper.database import Database
from recsniper.notifier import SMSNotifier
from recsniper.providers import get_provider

logger = logging.getLogger("recsniper.monitor")

# ---------------------------------------------------------------------------
# Timezone helpers
# ---------------------------------------------------------------------------

_TZ_ALIASES: Dict[str, timezone] = {
    "ET": timezone(timedelta(hours=-5)),
    "EST": timezone(timedelta(hours=-5)),
    "EDT": timezone(timedelta(hours=-4)),
    "CT": timezone(timedelta(hours=-6)),
    "CST": timezone(timedelta(hours=-6)),
    "CDT": timezone(timedelta(hours=-5)),
    "MT": timezone(timedelta(hours=-7)),
    "MST": timezone(timedelta(hours=-7)),
    "MDT": timezone(timedelta(hours=-6)),
    "PT": timezone(timedelta(hours=-8)),
    "PST": timezone(timedelta(hours=-8)),
    "PDT": timezone(timedelta(hours=-7)),
}

# Regex: "7:00 PM ET", "10:00 ET", "07:00 AM PDT", "07:00", etc.
_DROP_TIME_RE = re.compile(
    r"^(\d{1,2}):(\d{2})\s*(AM|PM)?(?:\s*([A-Z]{2,3}))?$", re.IGNORECASE
)


def _parse_drop_time(raw: str) -> tuple[int, int, timezone]:
    """Parse a drop-time string and return (hour_24, minute, tz)."""
    m = _DROP_TIME_RE.match(raw.strip())
    if not m:
        raise ValueError(
            f"Invalid drop_time format '{raw}'. Expected e.g. '10:00 ET' or '7:00 PM MT'."
        )

    hour, minute = int(m.group(1)), int(m.group(2))
    ampm = (m.group(3) or "").upper()
    tz_label = (m.group(4) or "PT").upper()

    # 12-hour → 24-hour conversion
    if ampm == "PM" and hour != 12:
        hour += 12
    elif ampm == "AM" and hour == 12:
        hour = 0

    if tz_label not in _TZ_ALIASES:
        raise ValueError(
            f"Unknown timezone abbreviation '{tz_label}'. "
            f"Supported: {', '.join(sorted(_TZ_ALIASES))}"
        )

    return hour, minute, _TZ_ALIASES[tz_label]


# ---------------------------------------------------------------------------
# Burst-check helper
# ---------------------------------------------------------------------------

_BURST_INTERVAL_SECONDS = 3
_BURST_DURATION_SECONDS = 90


# ---------------------------------------------------------------------------
# MonitorEngine
# ---------------------------------------------------------------------------


class MonitorEngine:
    """Schedules and executes availability checks for all active watches."""

    def __init__(
        self,
        db: Database,
        notifier: SMSNotifier,
        event_callback: Optional[Callable[[EventLog], Awaitable[None]]] = None,
    ):
        """
        Parameters
        ----------
        db : Database
            Async database handle.
        notifier : SMSNotifier
            SMS notification sender.
        event_callback : callable, optional
            An *async* callable invoked with every ``EventLog`` generated by the
            engine.  The FastAPI SSE endpoint wires this up to broadcast events
            to connected dashboards.
        """
        self.db = db
        self.notifier = notifier
        self.event_callback = event_callback

        self.scheduler = AsyncIOScheduler(
            timezone="UTC",
            job_defaults={"coalesce": True, "max_instances": 3, "misfire_grace_time": 30}
        )

        # Dedup: watch_id -> set of "site_id_date" keys already seen
        self._seen_slots: Dict[str, Set[str]] = {}

        # Active: watch_id -> set of currently available site_ids
        self._active_availabilities: Dict[str, Set[str]] = {}

        self.start_time: Optional[datetime] = None
        self.total_checks: int = 0

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """Load active watches from the database and start the scheduler."""
        self.start_time = datetime.utcnow()
        watches = await self.db.list_watches()
        for watch in watches:
            if watch.status in (WatchStatus.ACTIVE, WatchStatus.TRIGGERED):
                try:
                    await self._schedule_watch(watch)
                except Exception as exc:
                    logger.error("Failed to schedule watch %s (%s): %s", watch.id, watch.name, exc)
        self.scheduler.start()
        logger.info(
            "MonitorEngine started – %d active/triggered watches loaded.",
            sum(1 for w in watches if w.status in (WatchStatus.ACTIVE, WatchStatus.TRIGGERED)),
        )

    async def stop(self) -> None:
        """Shut down the scheduler gracefully."""
        if self.scheduler.running:
            self.scheduler.shutdown(wait=False)
            logger.info("MonitorEngine stopped.")

    # ------------------------------------------------------------------
    # Scheduling
    # ------------------------------------------------------------------

    async def _schedule_watch(self, watch: Watch) -> None:
        """Add APScheduler jobs appropriate for the watch's mode."""
        job_id = f"watch_{watch.id}"

        # Remove any existing job for this watch first
        if self.scheduler.get_job(job_id):
            self.scheduler.remove_job(job_id)

        if watch.mode == WatchMode.DROP_TIME:
            await self._schedule_drop_time(watch)

        elif watch.mode == WatchMode.ONE_SHOT:
            # Fire once immediately
            self.scheduler.add_job(
                self._run_check,
                args=[watch.id],
                id=job_id,
                trigger=DateTrigger(run_date=datetime.utcnow()),
                replace_existing=True,
            )

        else:
            # CANCELLATION – recurring interval, first run immediately
            interval = max(watch.poll_interval_minutes or 15, 1)
            self.scheduler.add_job(
                self._run_check,
                args=[watch.id],
                id=job_id,
                trigger=IntervalTrigger(minutes=interval),
                next_run_time=datetime.utcnow(),
                replace_existing=True,
            )

    async def _schedule_drop_time(self, watch: Watch) -> None:
        """
        Schedule a drop-time watch:
        1. At the configured drop time each day, start a *burst* of checks
           every 3 seconds for 90 seconds.
        2. After the burst window closes, fall back to the normal poll interval.
        """
        if not watch.drop_time:
            logger.warning(
                "Watch %s is DROP_TIME mode but has no drop_time value – "
                "falling back to cancellation-style interval.",
                watch.id,
            )
            self.scheduler.add_job(
                self._run_check,
                args=[watch.id],
                id=f"watch_{watch.id}",
                trigger=IntervalTrigger(minutes=watch.poll_interval_minutes or 15),
                next_run_time=datetime.utcnow(),
                replace_existing=True,
            )
            return

        hour, minute, tz = _parse_drop_time(watch.drop_time)

        # Build cron trigger that fires once a day at the drop time (in UTC)
        # Convert drop time to UTC for the CronTrigger
        drop_offset = tz.utcoffset(None)
        utc_hour = (hour - int(drop_offset.total_seconds() // 3600)) % 24
        utc_minute = minute

        # Daily cron that kicks off the burst
        self.scheduler.add_job(
            self._burst_check,
            args=[watch.id],
            id=f"watch_{watch.id}_burst_trigger",
            trigger=CronTrigger(hour=utc_hour, minute=utc_minute),
            replace_existing=True,
        )

        # Also schedule a normal fallback interval so the watch keeps running
        # outside the burst window.
        interval = max(watch.poll_interval_minutes or 10, 1)
        self.scheduler.add_job(
            self._run_check,
            args=[watch.id],
            id=f"watch_{watch.id}",
            trigger=IntervalTrigger(minutes=interval),
            next_run_time=datetime.utcnow(),
            replace_existing=True,
        )

        logger.info(
            "Scheduled DROP_TIME burst for watch %s at %02d:%02d UTC "
            "(parsed from '%s'), fallback every %d min.",
            watch.id,
            utc_hour,
            utc_minute,
            watch.drop_time,
            interval,
        )

    async def _burst_check(self, watch_id: str) -> None:
        """
        Perform rapid-fire checks for *_BURST_DURATION_SECONDS* at
        *_BURST_INTERVAL_SECONDS* intervals.
        """
        logger.info("⚡ Burst check started for watch %s", watch_id)

        burst_event = EventLog(
            event_type="burst_started",
            watch_id=watch_id,
            watch_name="",
            message="Drop-time burst check started – checking every 3 s for 90 s",
        )
        # Try to fill in watch name
        try:
            watch = await self.db.get_watch(watch_id)
            if watch:
                burst_event.watch_name = watch.name
        except Exception:
            pass

        await self.db.add_event_log(burst_event)
        if self.event_callback:
            await self.event_callback(burst_event)

        iterations = _BURST_DURATION_SECONDS // _BURST_INTERVAL_SECONDS
        for i in range(iterations):
            await self._run_check(watch_id)
            if i < iterations - 1:
                await asyncio.sleep(_BURST_INTERVAL_SECONDS)

        logger.info("⚡ Burst check finished for watch %s", watch_id)

    # ------------------------------------------------------------------
    # Core check logic
    # ------------------------------------------------------------------

    async def _run_check(self, watch_id: str, force: bool = False) -> None:
        """Execute a single availability check for *watch_id*."""
        watch = await self.db.get_watch(watch_id)
        if not watch:
            return
        if not force and watch.status not in (WatchStatus.ACTIVE, WatchStatus.TRIGGERED):
            return

        try:
            provider = get_provider(watch.reservation_type)
            slots: list[AvailabilitySlot] = await provider.check_availability(watch)
            self.total_checks += 1

            # Persist last_checked timestamp
            await self.db.update_watch(watch_id, last_checked=datetime.utcnow().isoformat())

            # Store availability records
            for slot in slots:
                try:
                    await self.db.add_availability_record(watch_id, watch.name, slot)
                except Exception as exc:
                    logger.debug("Failed to persist availability slot: %s", exc)

            # Store active availabilities for UI shading
            self._active_availabilities[watch_id] = {s.site_id for s in slots}

            # ----------------------------------------------------------
            # Diff against previously-seen slots to find *new* openings
            # ----------------------------------------------------------
            slot_keys = {f"{s.site_id}_{s.date}" for s in slots}
            prev_keys = self._seen_slots.get(watch_id, set())
            new_keys = slot_keys - prev_keys
            new_slots = [s for s in slots if f"{s.site_id}_{s.date}" in new_keys]
            self._seen_slots[watch_id] = slot_keys

            # ----------------------------------------------------------
            # Log the check
            # ----------------------------------------------------------
            if slots:
                message = f"Found {len(slots)} available slot(s) ({len(new_slots)} new)"
            else:
                message = "No availability found"

            event = EventLog(
                event_type="availability_found" if new_slots else "check_complete",
                watch_id=watch_id,
                watch_name=watch.name,
                message=message,
                details={"total": len(slots), "new": len(new_slots)},
            )
            await self.db.add_event_log(event)
            if self.event_callback:
                await self.event_callback(event)

            # ----------------------------------------------------------
            # Send SMS for genuinely new slots (with dedup guard)
            # ----------------------------------------------------------
            if new_slots:
                if watch.status != WatchStatus.TRIGGERED:
                    await self.db.update_watch(watch_id, status=WatchStatus.TRIGGERED.value)

                to_notify_slots = []
                for slot in new_slots:
                    slot_key = f"{slot.site_id}_{slot.date}"
                    if await self.db.was_recently_notified(watch_id, slot_key=slot_key):
                        logger.debug("Skipping duplicate notification for %s", slot_key)
                        continue
                    to_notify_slots.append(slot)

                if to_notify_slots:
                    success = await self.notifier.send_availability_alert(watch, to_notify_slots)
                    if success:
                        for slot in to_notify_slots:
                            slot_key = f"{slot.site_id}_{slot.date}"
                            await self.db.add_notification_log(
                                watch_id,
                                f"SMS sent for {slot.site_name} on {slot.date} ({slot_key})",
                            )
                            sms_event = EventLog(
                                event_type="sms_sent",
                                watch_id=watch_id,
                                watch_name=watch.name,
                                message=f"SMS alert sent: {slot.site_name} on {slot.date}",
                            )
                            await self.db.add_event_log(sms_event)
                            if self.event_callback:
                                await self.event_callback(sms_event)
            elif watch.status == WatchStatus.ERROR:
                # Clear error status back to active (or triggered if there are active availabilities)
                new_status = WatchStatus.TRIGGERED.value if slots else WatchStatus.ACTIVE.value
                await self.db.update_watch(watch_id, status=new_status)

            # ----------------------------------------------------------
            # Handle one-shot completion
            # ----------------------------------------------------------
            if watch.mode == WatchMode.ONE_SHOT:
                await self.db.update_watch(watch_id, status=WatchStatus.COMPLETED.value)
                completion_event = EventLog(
                    event_type="watch_completed",
                    watch_id=watch_id,
                    watch_name=watch.name,
                    message="One-shot check completed",
                )
                await self.db.add_event_log(completion_event)
                if self.event_callback:
                    await self.event_callback(completion_event)

        except Exception as exc:
            logger.error("Check failed for watch %s (%s): %s", watch_id, watch.name, exc)
            await self.db.update_watch(watch_id, status=WatchStatus.ERROR.value)
            error_event = EventLog(
                event_type="error",
                watch_id=watch_id,
                watch_name=watch.name,
                message=f"Check failed: {str(exc)}",
            )
            await self.db.add_event_log(error_event)
            if self.event_callback:
                await self.event_callback(error_event)

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    async def run_check_now(self, watch_id: str) -> None:
        """Trigger an immediate check for a specific watch (called by API)."""
        await self._run_check(watch_id, force=True)

    async def add_watch(self, watch: Watch) -> None:
        """Register a new watch with the scheduler."""
        if watch.status in (WatchStatus.ACTIVE, WatchStatus.TRIGGERED):
            await self._schedule_watch(watch)

    async def remove_watch(self, watch_id: str) -> None:
        """Remove all scheduler jobs associated with *watch_id*."""
        for suffix in ("", "_burst_trigger"):
            job_id = f"watch_{watch_id}{suffix}"
            if self.scheduler.get_job(job_id):
                self.scheduler.remove_job(job_id)
        self._seen_slots.pop(watch_id, None)

    async def reschedule_watch(self, watch: Watch) -> None:
        """Remove then re-add a watch (useful after edits)."""
        await self.remove_watch(watch.id)
        await self.add_watch(watch)

    def get_status(self) -> dict:
        """Return a JSON-friendly engine status summary."""
        uptime = (
            (datetime.utcnow() - self.start_time).total_seconds()
            if self.start_time
            else 0
        )
        jobs = self.scheduler.get_jobs() if self.scheduler.running else []
        next_run = None
        if jobs:
            run_times = [j.next_run_time for j in jobs if j.next_run_time is not None]
            if run_times:
                next_run = min(run_times)

        return {
            "running": self.scheduler.running if self.scheduler else False,
            "uptime_seconds": int(uptime),
            "active_watches": len([j for j in jobs if not j.id.endswith("_burst_trigger")]),
            "total_checks": self.total_checks,
            "next_check": next_run.isoformat() if next_run else None,
        }
